name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile C program
        run: gcc -o my_program main.c

      - name : Put the program in the PATH
        uses : actions/upload-artifact@v4
        with : 
            name : my_program
            path : my_program
        

  test :
    needs : build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download the program
        uses: actions/download-artifact@v4
        with:
         name: my_program
         

      - name: Give execution permission
        run: chmod +x my_program
        
      - name: Run tests
        run: |
          if ./my_program; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
 